apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  namespace: frontend
  labels:
    app: tripviewer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      - name: tripviewer
        image: registrykdu8597.azurecr.io/tripviewer:3.1
        ports:
        - containerPort: 80
        env:
        - name: TRIPS_API_ENDPOINT
          value: "http://trips-svc"
        - name: USERPROFILE_API_ENDPOINT
          value: "http://user-profile-svc"
        - name: NAME
          value: "Kubernetes"
     