apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  labels:
    app: user-java-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registrykdu8597.azurecr.io/user-java:3.1
        ports:
        - containerPort: 80
        env:
        - name: SQL_USER
          value: "sqladminkDu8597"
        - name: SQL_PASSWORD
          value: "mA4xr7Tz0"
        - name: SQL_SERVER
          value: "sqlserverkdu8597.database.windows.net"
        - name: SQL_DBNAME
          value: "mydrivingDB"
        - name: PORT
          value: "80"
