apiVersion: v1
kind: Service
metadata:
  name: tripviewer-svc
  labels:
    app: tripviewer-svc
spec:
  type: LoadBalancer
  ports:
  - port: 80
    protocol: TCP
  selector:
    app: tripviewer
  type: LoadBalancer