apiVersion: apps/v1
kind: Deployment
metadata:
  name: tripviewer-deployment
  labels:
    app: tripviewer-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: tripviewer
  template:
    metadata:
      labels:
        app: tripviewer
    spec:
      containers:
      env:
      - name: TRIPS_API_ENDPOINT
        value: "http://trips-svc"
      - name: USERPROFILE_API_ENDPOINT
        value: "http://user-profile-svc"
      - name: NAME
      value: "Kubernetes"
      - name: tripviewer
        image: registrykdu8597.azurecr.io/tripviewer:2.0
        ports:
        - containerPort: 80