apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile-deployment
  labels:
    app: user-profile-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-profile
  template:
    metadata:
      labels:
        app: user-profile
    spec:
      containers:
      - name: user-profile
        image: registrykdu8597.azurecr.io/user_profile:2.0
        ports:
        - containerPort: 80