apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-java
  labels:
    app: user-java-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-java
  template:
    metadata:
      labels:
        app: user-java
    spec:
      containers:
      - name: user-java
        image: registrykdu8597.azurecr.io/user-java:2.0
        ports:
        - containerPort: 80