apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: poi-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /api/poi
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: poi-api-svc
          servicePort: 80
        path: /api/poi
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: trips-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /api/trips
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: trips-svc
          servicePort: 80
        path: /api/trips
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: user-java-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /api/user-java
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: user-java-svc
          servicePort: 80
        path: /api/user-java
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: user-profile-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /api/user
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: user-profile-svc
          servicePort: 80
        path: /api/user
---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: insurance-ingress
  namespace: api
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /api/insurance
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: insurance
          servicePort: 80
        path: /api/insurance