apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: tripviewer-ingress
  namespace: frontend
  annotations:
    kubernetes.io/ingress.class: nginx
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - http:
      paths:
      - backend:
          serviceName: tripviewer-svc
          servicePort: 80
        path: /