apiVersion: apps/v1
kind: Deployment
metadata:
  name: poi-api-deployment
  namespace: api
  labels:
    app: poi-api-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi-api
  template:
    metadata:
      labels:
        app: poi-api
    spec:
      containers:
      - name: poi-api
        image: registrykdu8597.azurecr.io/poi_api:4.1
        ports:
        - containerPort: 80
          name: http
        volumeMounts:
        - name: keyvault
          mountPath: /kvmnt
          readOnly: true
      volumes:
      - name: keyvault
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds
          options:
            keyvaultname: "team5keyvault"
        - name: ASPNETCORE_ENVIRONMENT
            keyvaultobjectnames: "SQLUSER;SQLPASSWORD;SQLSERVER;SQLDBNAME"
            keyvaultobjecttypes: "secret;secret;secret;secret"
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DNName"
            resourcegroup: "teamResources"
            subscriptionid: "d960cdba-b4f2-4b73-b2f8-b54c29b18332"
            tenantid: "OTAPRD1603ops.onmicrosoft.com"
        env: 
        - name: WEB_PORT
          value: "80"
        - name: WEB_SERVER_BASE_URI
          value: "http://0.0.0.0"
        - name: ASPNETCORE_ENVIRONMENT
          value: "Development"
        - name: CONFIG_FILES_PATH
          value: "/secrets"
         
   