apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: poi-api-deployment
  name: poi-api-deployment
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: poi-api
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: poi-api
    spec:
      containers:
      - env:
        - name: WEB_PORT
          value: "80"
        - name: WEB_SERVER_BASE_URI
          value: http://0.0.0.0
        - name: ASPNETCORE_ENVIRONMENT
          value: Development
        - name: CONFIG_FILES_PATH
          value: /secrets
        image: registrykdu8597.azurecr.io/poi_api:4.1
        name: poi-api
        ports:
        - containerPort: 80
          name: http
        resources: {}
        volumeMounts:
        - mountPath: /kvmnt
          name: keyvault
          readOnly: true
      volumes:
      - flexVolume:
          driver: azure/kv
          options:
            keyvaultname: team5keyvault
            keyvaultobjectaliases: SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DNName
            keyvaultobjectnames: SQLUSER;SQLPASSWORD;SQLSERVER;SQLDBNAME
            keyvaultobjecttypes: secret;secret;secret;secret
            resourcegroup: teamResources
            subscriptionid: d960cdba-b4f2-4b73-b2f8-b54c29b18332
            tenantid: OTAPRD1603ops.onmicrosoft.com
          secretRef:
            name: kvcreds
        name: keyvault
status: {}
---
