apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: trips-deployment
  name: trips-deployment
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: trips
    spec:
      containers:
      - env:
        - name: PORT
          value: "80"
        - name: OPENAPI_DOCS_URI
          value: http://changeme
        - name: DEBUG_LOGGING
          value: "false"
        - name: CONFIG_FILES_PATH
          value: /secrets
        image: registrykdu8597.azurecr.io/trips:4.1
        name: trips
        ports:
        - containerPort: 80
        resources: {}
      volumes:
      - flexVolume:
          driver: azure/kv
          options:
            keyvaultname: team5keyvault
            keyvaultobjectaliases: SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DBNAME
            keyvaultobjectnames: SQLUSER;SQLPASSWORD;SQLSERVER;SQLDBNAME
            keyvaultobjecttypes: secret;secret;secret;secret
            resourcegroup: teamResources
            subscriptionid: d960cdba-b4f2-4b73-b2f8-b54c29b18332
            tenantid: OTAPRD1603ops.onmicrosoft.com
          secretRef:
            name: kvcreds
        name: keyvault
status: {}
---
