apiVersion: apps/v1
kind: Deployment
metadata:
  name: trips-deployment
  namespace: api
  labels:
    app: trips-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: trips
  template:
    metadata:
      labels:
        app: trips
    spec:
      containers:
      - name: trips
        image: registrykdu8597.azurecr.io/trips:4.1
        ports:
        - containerPort: 80
        env:
        - name: PORT
          value: "80"
        - name: OPENAPI_DOCS_URI
          value: "http://changeme"
        - name: DEBUG_LOGGING
          value: "false"
        - name: CONFIG_FILES_PATH
          value: "/secrets"
      volumes:
      - name: keyvault
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds
          options:
            keyvaultname: "team5keyvault"
            keyvaultobjectnames: "SQLUSER;SQLPASSWORD;SQLSERVER;SQLDBNAME"
            keyvaultobjecttypes: "secret;secret;secret;secret"
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DBNAME"
            resourcegroup: "teamResources"
            subscriptionid: "d960cdba-b4f2-4b73-b2f8-b54c29b18332"
            tenantid: "OTAPRD1603ops.onmicrosoft.com"