apiVersion: apps/v1
kind: Deployment
metadata:
  name: user-profile-deployment
  namespace: api
  labels:
    app: user-profile-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: user-profile
  template:
    metadata:
      labels:
        app: user-profile
    spec:
      containers:
      - name: user-profile
        image: registrykdu8597.azurecr.io/user_profile:3.1
        ports:
        - containerPort: 80
        volumeMounts:
        - name: keyvault
          mountPath: /kvmnt
          readOnly: true
        env:
        - name: PORT
          value: "80"
        - name: CONFIG_FILES_PATH
          value: "/secrets"
      volumes:
      - name: keyvault
        flexVolume:
          driver: "azure/kv"
          secretRef:
            name: kvcreds
          options:
            keyvaultname: "team5keyvault"
            keyvaultobjectnames: "SQLUSER;SQLPASSWORD;SQLSERVER;SQLDBNAME"
            keyvaultobjecttypes: "secret;secret;secret;secret"
            keyvaultobjectaliases: "SQL_USER;SQL_PASSWORD;SQL_SERVER;SQL_DBNAME"
            resourcegroup: "teamResources"
            subscriptionid: "d960cdba-b4f2-4b73-b2f8-b54c29b18332"
            tenantid: "OTAPRD1603ops.onmicrosoft.com"
          