apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    deploy: insurance
  name: insurance-deployment
  namespace: api
spec:
  replicas: 2
  selector:
    matchLabels:
      app: insurance
  strategy: {}
  template:
    metadata:
      annotations:
        linkerd.io/inject: enabled
      creationTimestamp: null
      labels:
        app: insurance
    spec:
      containers:
      - image: registrykdu8597.azurecr.io/insurance:1.0
        imagePullPolicy: Always
        name: insurance
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 200m
            memory: 3096Mi
          requests:
            cpu: 100m
            memory: 64Mi
status: {}
---
apiVersion: v1
kind: Service
metadata:
  name: insurance
  namespace: api
spec:
  type: ClusterIP
  selector:
    app: insurance
  ports:
  - protocol: TCP
    name: insurance-http
    port: 80
    targetPort: 8081
---
