kind: Role
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: dev-user-read-access
  namespace: api
rules:
- apiGroups: ["", "extensions", "apps"]
  resources: ["pods", "services"]
  verbs: ["get", "watch", "list"]