kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: frontend-user-access
  namespace: frontend
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: frontend-user-full-access
subjects:
- kind: User
  namespace: frontend
  name: webdev@OTAPRD1603ops.onmicrosoft.com
